export const DEFAULT_IDEAS = [
  {
    id: 1, title: "Free Telescope Viewings", emoji: "🔭",
    location: "Chabot Space & Science Center, 10000 Skyline Blvd, Oakland, CA 94619",
    lat: 37.8197, lng: -122.1791,
    when: "Every Friday & Saturday, 7:30–10:30 PM (year-round)",
    eventDate: null,
    cost: "FREE — no admission needed for the observatory deck", costBadge: "FREE",
    description: 'Stargaze through three historic telescopes 1,500 ft above the Bay with volunteer astronomers guiding the experience. Peer at stars, planets, and deep-sky objects through Leah (8", 1883), Rachel (20", 1916) — the largest public refractor in the Western U.S. — and Nellie, a powerful 36" modern reflector.',
    notes: [
      "No reservations needed — just show up on a Fri or Sat night",
      "Weather-dependent: telescopes close if raining or humidity is too high",
      "Check chabotspace.org/weather-station before heading out",
      "Volunteers are usually on-site even in cloudy weather to explain the telescopes",
    ],
    tags: ["Outdoor","Free","Science","Nighttime"],
    link: "https://chabotspace.org/programs/free-telescope-viewings/",
  },
  {
    id: 2, title: "Stanford Live at Bing Concert Hall", emoji: "🎻",
    location: "Bing Concert Hall, 327 Lasuen St, Stanford, CA",
    lat: 37.4269, lng: -122.1670,
    when: "Frequent Friday & Saturday evenings — check live.stanford.edu",
    eventDate: null,
    cost: "$32–$37 per person (~$65–$74 for two). Parking free on weekends.", costBadge: "$65–$74 for 2",
    description: "World-class classical music, chamber ensembles, opera, and more — right on the Stanford campus. The acoustics were designed by Yasuhisa Toyota, who also did Walt Disney Concert Hall.",
    notes: [
      "Tickets at live.stanford.edu — book ahead as popular shows sell out",
      "Free parking on Stanford campus on weekends",
      "Doors open one hour before performances",
      "Some concerts are free or heavily discounted — check the calendar",
    ],
    tags: ["Music","Indoor","Classical"],
    link: "https://live.stanford.edu/",
  },
  {
    id: 3, title: "Sea Kayaking at Pillar Point Harbor", emoji: "🚣",
    location: "Half Moon Bay Kayak Co., 2 Johnson Pier, Half Moon Bay, CA",
    lat: 37.4957, lng: -122.4956,
    when: "Daily 10am–4pm. Best on calm mornings.",
    eventDate: null,
    cost: "$60/hr or $150/day for a double kayak. 2-hour paddle ~$120 for two.", costBadge: "~$120 for 2",
    description: "Paddle a double kayak among harbor seals, sea lions, and pelicans in the protected waters of Pillar Point Harbor. All gear provided including wetsuits and paddle jackets.",
    notes: [
      "No experience necessary — staff give thorough instructions",
      "Gear provided: wetsuits, life jackets, paddle jackets, dry bags",
      "Call ahead to check conditions: hmbkayak.com",
      "Pair with a coastal trail walk or lunch in Half Moon Bay afterward",
    ],
    tags: ["Outdoor","Adventure","Water","Active"],
    link: "https://www.hmbkayak.com/",
  },
  {
    id: 4, title: "Monte Bello Open Space Preserve Hike", emoji: "🥾",
    location: "4185 Page Mill Rd, Palo Alto, CA",
    lat: 37.3186, lng: -122.1544,
    when: "Any day, sunrise to sunset.",
    eventDate: null,
    cost: "FREE — free parking at trailhead", costBadge: "FREE",
    description: "Your closest 'wow' hike — right above Palo Alto. 360° views spanning SF Bay to the Pacific Ocean. The 7-mile Monte Bello Loop gains 1,371 ft. The Stevens Creek Nature Trail follows the San Andreas Fault.",
    notes: [
      "Trailhead parking fills early on weekends — go before 9am",
      "No dogs allowed on trails",
      "No cell service — download a map before you go",
      "Pack a picnic to enjoy at the summit with the views",
    ],
    tags: ["Outdoor","Free","Active","Hiking"],
    link: "https://www.openspace.org/preserves/monte-bello",
  },
  {
    id: 5, title: "Exploratorium After Dark (Adults Only)", emoji: "🔬",
    location: "Pier 15, The Embarcadero, San Francisco, CA",
    lat: 37.8017, lng: -122.3973,
    when: "Every Thursday evening, 6–10 PM.",
    eventDate: null,
    cost: "~$30–$40 per person (~$60–$80 for two)", costBadge: "$60–$80 for 2",
    description: "The Exploratorium transforms into an adults-only science and art playground every Thursday night. Cocktails in hand, explore 700+ interactive exhibits — all without kids underfoot.",
    notes: [
      "Book at exploratorium.edu/visit/calendar/after-dark",
      "Tactile Dome is very popular — get tickets on arrival",
      "Cash bar available (21+)",
      "Combine with dinner on the Embarcadero before or after",
    ],
    tags: ["Science","Indoor","Nighttime","Active"],
    link: "https://www.exploratorium.edu/visit/calendar/after-dark",
  },
  {
    id: 6, title: "The Wave Organ + Marina Waterfront Walk", emoji: "🌊",
    location: "1 Yacht Rd, San Francisco, CA (end of the Marina jetty)",
    lat: 37.8063, lng: -122.4370,
    when: "Always open. Best at high tide.",
    eventDate: null,
    cost: "FREE", costBadge: "FREE",
    description: "An acoustic sculpture with 25 PVC pipes extending into the Bay. As waves push air through the pipes they produce strange, beautiful liquid music. Pair with a walk along Crissy Field toward the Golden Gate.",
    notes: [
      "Visit at high tide for the best sounds — check tideschart.com",
      "Get your ears close to the pipe openings",
      "Best combined with a walk west toward the Golden Gate",
      "Free parking in the Marina",
    ],
    tags: ["Outdoor","Free","Science","Art"],
    link: "https://www.exploratorium.edu/visit/wave-organ",
  },
  {
    id: 7, title: "Danish String Quartet & Danish National Girls' Choir", emoji: "🎼",
    location: "Bing Concert Hall, 327 Lasuen St, Stanford, CA",
    lat: 37.4269, lng: -122.1670,
    when: "Wednesday, April 15, 2026 at 7:30 PM. Pre-concert talk at 6:45 PM.",
    eventDate: "2026-04-15",
    cost: "~$78/person avg (~$156 for two). Stanford Alumni members get 10% off.", costBadge: "~$156 for 2",
    description: "The Grammy-nominated Danish String Quartet joins the Danish National Girls' Choir for the only Bay Area stop of their US tour. They premiere 'in wildness' — a Stanford Live co-commission by Pulitzer Prize-winning composer David Lang.",
    notes: [
      "Pre-concert talk at 6:45 PM with David Lang and choir director Charlotte Rowan — free for ticketholders",
      "Tickets unavailable online — call the Bing Concert Hall box office",
      "Stanford Alumni Association members get 10% off single tickets",
      "Only Bay Area date — tour heads to Carnegie Hall on Apr 17",
      "Free parking on Stanford campus in the evening",
    ],
    tags: ["Music","Indoor","Classical","Splurge"],
    link: "https://live.stanford.edu/events/25-26season/bing-concert-hall/danish-string-quartet-and-danish-national-girls-choir/",
  },
  {
    id: 8, title: "Palo Alto Philharmonic — Dvořák Cello Concerto", emoji: "🎻",
    location: "Cubberley Theatre, 4120 Middlefield Rd, Palo Alto, CA",
    lat: 37.4088, lng: -122.1100,
    when: "Saturday, April 11, 2026 at 7:30 PM",
    eventDate: "2026-04-11",
    cost: "$25/person ($50 for two). $10 students. Buy at paphil.org or at the door.", costBadge: "$50 for 2",
    description: "Your community orchestra performs Sibelius's Karelia Overture, Britten's Four Sea Interludes from Peter Grimes, and Dvořák's sweeping Cello Concerto with soloist Evan Kahn — former principal cellist of San Francisco Opera.",
    notes: [
      "Tickets at paphil.org or at the door — box office opens 30 min before",
      "Pre-concert talk at 7:15 PM",
      "Cubberley Theatre has comfortable seating and free parking",
      "The Dvořák Cello Concerto is widely considered one of the greatest concertos ever written",
    ],
    tags: ["Music","Indoor","Classical"],
    link: "https://www.paphil.org/performances",
  },
  {
    id: 9, title: "Händel Dixit Dominus — All Saints Episcopal Church", emoji: "🎼",
    location: "All Saints Episcopal Church, 555 Waverley St, Palo Alto, CA",
    lat: 37.4456, lng: -122.1596,
    when: "Sunday, April 5, 2026 at 7:00 PM",
    eventDate: "2026-04-05",
    cost: "Pay-what-you-will in advance; $15–$30 at the door.", costBadge: "Pay-what-you-will",
    description: "Händel's Dixit Dominus — one of the most thrillingly dramatic choral works of the Baroque era, written when he was just 22. Performed in the beautiful round sanctuary of All Saints, known locally for exceptional acoustics and music.",
    notes: [
      "All Saints is known for excellent acoustics and a welcoming atmosphere",
      "Pay-what-you-will ticketing makes this very accessible",
      "Just minutes from downtown Palo Alto — easy to make a dinner date of it",
      "Check asaints.org closer to the date for full program details",
    ],
    tags: ["Music","Indoor","Classical","Free"],
    link: "https://www.asaints.org/",
  },
  {
    id: 10, title: "Learn to Curl — Silicon Valley Curling Club", emoji: "🥌",
    location: "Sharks Ice at San Jose, 1500 S 10th St, San Jose, CA",
    lat: 37.3229, lng: -121.8683,
    when: "Sessions throughout the year — check siliconvalleycurling.com/ltc/ for upcoming dates.",
    eventDate: null,
    cost: "~$40/person (~$80 for two). Check website for current pricing.", costBadge: "~$80 for 2",
    description: "The Silicon Valley Curling Club runs 2-hour Learn to Curl sessions at Sharks Ice in San Jose. Safety briefing, delivering stones, sweeping, and a mini-game — no experience needed. Genuinely fun, a little absurd, and surprisingly athletic.",
    notes: [
      "No experience or equipment needed — everything provided including shoe sliders",
      "Wear warm, comfortable layers and flat-soled athletic shoes",
      "Sessions fill up quickly — book ahead at siliconvalleycurling.com/ltc/",
      "After Learn to Curl you're eligible to join their drop-in leagues",
    ],
    tags: ["Active","Indoor","Adventure"],
    link: "https://siliconvalleycurling.com/ltc/",
  },
  {
    id: 11, title: "Echoes of Andalusia — Adam del Monte, Solo Guitar", emoji: "🎸",
    location: "De Anza College, VPAC Theatre, 21250 Stevens Creek Blvd, Cupertino, CA",
    lat: 37.3196, lng: -122.0452,
    when: "Tuesday, April 28, 2026. Doors open 45 min before start.",
    eventDate: "2026-04-28",
    cost: "$49 early bird / $59 standard (~$98–$118 for two). No added service fees.", costBadge: "$98–$118 for 2",
    description: "Adam del Monte — Deutsche Grammophon artist, Carnegie Hall performer — plays a solo flamenco/classical guitar program: Albéniz's Granada, Sevilla, Torre Berméja alongside his own Soleá, Alegrias, Guajira and more. About 75 minutes, deeply transportive.",
    notes: [
      "⚠️ Cupertino shows as sold out online — extra seats may be available at the door",
      "Other Bay Area dates: SF (Apr 23), Oakland (Apr 25), Berkeley (Apr 26)",
      "General admission — arrive early for good seats",
      "Tickets non-refundable but transferable to friends/family",
    ],
    tags: ["Music","Indoor","Classical"],
    link: "https://concertsinamerica.com/andalusia/",
  },
];

export const TAG_COLORS = {
  Outdoor:    { bg: "#dcfce7", text: "#16a34a", border: "#bbf7d0" },
  Free:       { bg: "#fef9c3", text: "#a16207", border: "#fef08a" },
  Science:    { bg: "#dbeafe", text: "#1d4ed8", border: "#bfdbfe" },
  Nighttime:  { bg: "#f3e8ff", text: "#7e22ce", border: "#e9d5ff" },
  Indoor:     { bg: "#f1f5f9", text: "#475569", border: "#e2e8f0" },
  Music:      { bg: "#fce7f3", text: "#be185d", border: "#fbcfe8" },
  Adventure:  { bg: "#d1fae5", text: "#065f46", border: "#a7f3d0" },
  Classical:  { bg: "#ede9fe", text: "#6d28d9", border: "#ddd6fe" },
  Water:      { bg: "#cffafe", text: "#0e7490", border: "#a5f3fc" },
  Active:     { bg: "#fef3c7", text: "#b45309", border: "#fde68a" },
  Hiking:     { bg: "#d1fae5", text: "#065f46", border: "#a7f3d0" },
  Art:        { bg: "#fce7f3", text: "#be185d", border: "#fbcfe8" },
  Splurge:    { bg: "#fef2f2", text: "#b91c1c", border: "#fecaca" },
  Suggestion: { bg: "#f0f9ff", text: "#0369a1", border: "#bae6fd" },
};

// Storage keys — bump suffix to reset all persisted state
export const KEYS = {
  DONE:      "ldi-done-v1",
  ARCHIVE:   "ldi-archive-v1",
  REACTIONS: "ldi-reactions-v1",   // { [ideaId]: { [userName]: "🔥"|"👍"|"🤔"|"👎" } }
  USER:      "ldi-user-v1",
  EXTRA:     "ldi-extra-v1",
};
